Default: &defaults
  database: chatexample.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: chatexample_test.sqlite3
  <<: *defaults

Staging:
  database: chatexample_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: chatexample_production.sqlite3
  poolsize: 100
  <<: *defaults
